export default [
    "Maine Coon",
    "Ragamuffin",
    "Ragdoll",
    "Persian",
    "American Shorthair",
    "Abyssinian",
    "Siamese",
    "Tonkinese",
    "Russian Blue",
    "Bengal",
    "Scottish Fold",
    "British Shorthair",
    "Siberian",
    "Exotic",
    "Birman",
    "Himalayan",
    "Nebelung",
    "Norwegian Forest",
    "American Bobtail",
    "Bombay",
    "Burmese",
    "Chartreux",
    "Chinese Li Hua",
    "Devon Rex",
    "Ocicat"
]